[tool.poetry]
name = "tennis-match-scoreboard"
version = "0.1.0"
description = "Tennis match tracking application"
packages = [{include = "tennis_match_scoreboard", from = "src"}]

[tool.poetry.scripts]
tennis-match-scoreboard = "tennis_match_scoreboard.application:main"