"""remove nullable=True

Revision ID: 2657fd8b03c2
Revises: f354cd6c606f
Create Date: 2025-10-13 16:20:30.785322

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '2657fd8b03c2'
down_revision: Union[str, Sequence[str], None] = 'f354cd6c606f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches_table', 'player1_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('matches_table', 'player2_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('matches_table', 'winner',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_players_table_name'), 'players_table', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем индекс для имени игрока
    op.drop_index(op.f('ix_players_table_name'), table_name='players_table')

    # Возвращаем nullable обратно
    op.alter_column('matches_table', 'winner',
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    op.alter_column('matches_table', 'player2_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    op.alter_column('matches_table', 'player1_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
