"""Create initial tables for players and matches

Revision ID: 4a9a599d4505
Revises: 
Create Date: 2025-09-28 22:21:58.010766

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '4a9a599d4505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
