"""String -> Uuid

Revision ID: 5c238251abb3
Revises: 69a3fb958b66
Create Date: 2025-11-16 15:03:18.155185

"""
import uuid
from typing import Sequence, Union

import sqlalchemy
from alembic import op
import sqlalchemy as sa
from select import select
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c238251abb3'
down_revision: Union[str, Sequence[str], None] = '69a3fb958b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

matches_table = sa.table(
    'matches_table',
    sa.column('id', sa.Integer),
    sa.column('uuid', sa.String(36)),  # Старый тип
    sa.column('uuid_temp', sa.Uuid)   # Новый тип
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches_table', sa.Column('uuid_temp', sa.Uuid(), nullable=True))

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    for match in session.query(matches_table).filter(matches_table.c.uuid != None):
        uuid_object = uuid.UUID(match.uuid)

        session.execute(
            sa.update(matches_table).where(matches_table.c.id == match.id).values(uuid_temp=uuid_object)
        )
    session.commit()
    op.drop_column('matches_table', 'uuid')

    op.alter_column('matches_table', 'uuid_temp', new_column_name='uuid', existing_type=sa.Uuid(), nullable=False,
                    existing_nullable=True)

    op.create_unique_constraint("uq_matches_table_uuid", "matches_table", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    matches_table_downgrade = sa.table(
        'matches_table',
        sa.column('id', sa.Integer),
        sa.column('uuid', sa.Uuid()),  # Старый тип (для downgrade)
        sa.column('uuid_temp', sa.String(36))  # Новый тип (для downgrade)
    )

    op.add_column('matches_table', sa.Column('uuid_temp', sa.String(36), nullable=True))

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    for match in session.query(matches_table_downgrade).filter(matches_table_downgrade.c.uuid != None):
        uuid_string = str(match.uuid)
        session.execute(
            sa.update(matches_table_downgrade)
            .where(matches_table_downgrade.c.id == match.id)
            .values(uuid_temp=uuid_string)
        )
    session.commit()

    op.drop_constraint("uq_matches_table_uuid", "matches_table", type_='unique')

    op.drop_column('matches_table', 'uuid')

    op.alter_column(
        'matches_table',
        'uuid_temp',
        new_column_name='uuid',
        existing_type=sa.String(36),
        nullable=False,
        existing_nullable=True
    )
    op.create_unique_constraint("uq_matches_table_uuid", "matches_table", ["uuid"])