"""String -> Text

Revision ID: 69a3fb958b66
Revises: f6481a961028
Create Date: 2025-11-16 14:46:35.638799

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69a3fb958b66'
down_revision: Union[str, Sequence[str], None] = 'f6481a961028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_table_name'), table_name='players_table')
    op.alter_column('players_table', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=30),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_players_table_name'), 'players_table', ['name'], unique=False, mysql_length=255)

    op.alter_column('matches_table', 'score',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=250),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_table_name'), table_name='players_table')
    op.alter_column('players_table', 'name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_players_table_name'), 'players_table', ['name'], unique=False)

    op.alter_column('matches_table', 'score',
                    existing_type=sa.Text(),
                    type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=250),
                    existing_nullable=False)
    # ### end Alembic commands ###
