"""make matches.winner nullable

Revision ID: c8708b56e565
Revises: 4a9a599d4505
Create Date: 2025-10-04 00:35:31.671484

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'c8708b56e565'
down_revision: Union[str, Sequence[str], None] = '4a9a599d4505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
