"""initial schema

Revision ID: f6481a961028
Revises: 
Create Date: 2025-10-24 21:37:48.249503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6481a961028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_table_name'), 'players_table', ['name'], unique=False)
    op.create_table('matches_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('score', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['players_table.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players_table.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['players_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches_table')
    op.drop_index(op.f('ix_players_table_name'), table_name='players_table')
    op.drop_table('players_table')
    # ### end Alembic commands ###
